(load "./libpluto.lisp")
(in-package "libpluto")

(fresh-line)
(princ "System Initializing...")
(setq return_code (pluto_util_init_all "ip:192.168.2.1" 4096 4096))
(fresh-line)
(if (/= return_code 0) (princ "Initialize faild.") (princ "Initialized."))
(if (/= return_code 0) (quit))
(fresh-line) (princ "============")
(setq voltage (pluto_get_voltage))
(setq current (pluto_get_current))
(fresh-line)
(princ "System Voltage:") (write voltage) (princ " V")
(fresh-line)
(princ "System Current:") (write current) (princ " A")
(fresh-line)
(princ "System Power") (write (* voltage current)) (princ " W")
(fresh-line) (princ "============")
(fresh-line) 
(princ "Read power from RX...")
(pluto_util_set_tx_power 1420405752 200001 2083334 -1.0)
(loop
    (pluto_set_tx_en nil)
    (fresh-line) (princ "Calc power from RX?(y/n)")
    (setq key_in (read))
    (fresh-line)
    (if (string/= key_in "Y") (return))
    (pluto_set_tx_en t)
    (setq rx_pwr (* 10 (pluto_util_get_rx_power 1420405752 2000001 2083334)))
    (princ "Power: ") (write rx_pwr)
    )
(princ "Read canceled.")
(pluto_set_tx_en nil)
(pluto_destroy)
(fresh-line) (princ "Pluto destroied.")
